project_id = "pdgjafywsxesgwukotxh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://ca0dcc3f-38a5-4f85-b04a-6ae1254bb35c.lovableproject.com/**",
  "https://id-preview--ca0dcc3f-38a5-4f85-b04a-6ae1254bb35c.lovable.app/**",
  "https://moonshot-memestock-hub.lovable.app/**",
  "https://preview--moonshot-memestock-hub.lovable.app/**"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600

[edge_runtime]
enabled = true
inspector_port = 54331

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Setup BigQuery project to enable log viewer on local development stack.
# See: https://supabase.com/docs/guides/getting-started/local-development#enabling-local-logging
# gcp_project_id = ""
# gcp_project_number = ""
# gcp_jwt_path = "supabase/gcloud.json"

[functions.ai-sentiment-analysis]
verify_jwt = false

[functions.ai-sentiment-claude]
verify_jwt = false

[functions.bulk-historical-import]
verify_jwt = false

[functions.enhanced-market-data]
verify_jwt = false

[functions.enhanced-sentiment-analysis]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.financial-news]
verify_jwt = false

[functions.google-trends]
verify_jwt = false

[functions.polygon-market-data]
verify_jwt = false

[functions.reddit-auth]
verify_jwt = false

[functions.sentiment-backtesting]
verify_jwt = false

[functions.sentiment-score]
verify_jwt = false

[functions.stocktwits-data]
verify_jwt = false

[functions.twitter-sentiment]
verify_jwt = false

[functions.youtube-sentiment]
verify_jwt = false

[functions.reddit-backfill-import]
verify_jwt = false

[functions.reddit-queue-import]
verify_jwt = false

[functions.reddit-worker]
verify_jwt = false

[functions.reddit-queue-processor]
verify_jwt = false

[functions.close-paper-trade]
verify_jwt = false

[functions.reddit-loader-orchestrator]
verify_jwt = false

[functions.sentiment-score]
verify_jwt = false
