export const ALLOWED_SUBREDDITS = [
  "stocks",
  "investing",
  "SecurityAnalysis",
  "ValueInvesting",
  "StockMarket",
  "economy",
  "finance",
  "options",
  "wallstreetbets",
  "pennystocks",
  "robinhood",
  "RobinHoodPennyStocks",
  "smallstreetbets",
  "daytrading",
  "Superstonk",
  "personalfinance",
  "CryptoCurrency",
  "CryptoMarkets",
  "Bitcoin",
  "Fire",
  "financialindependence",
  "amcstock",
  "AMD_Stock",
  "NVDA_Stock",
  "portfolios",
  "altcoin",
  "bonds",
  "SPACs",
  "oil",
];

export const ALLOWED_SUBREDDITS_SET = new Set(
  ALLOWED_SUBREDDITS.map(name => name.toLowerCase()),
);
