
name: AI-Powered Backtesting Analysis

on:
  workflow_dispatch:
    inputs:
      symbol:
        description: 'Stock symbol to analyze'
        required: true
        default: 'AAPL'
      days:
        description: 'Number of days to analyze'
        required: true
        default: '30'
  repository_dispatch:
    types: [run-ai-backtest]

jobs:
  ai-backtesting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run AI Analysis
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node .github/scripts/ai-backtesting.js
        with:
          symbol: ${{ github.event.inputs.symbol || github.event.client_payload.symbol }}
          days: ${{ github.event.inputs.days || github.event.client_payload.days }}

      - name: Commit AI-generated strategy updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "AI Backtesting Bot"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "AI-generated backtesting strategy update for ${{ github.event.inputs.symbol || github.event.client_payload.symbol }}"
            git push
          fi
